### ISSUE TITLE
TEST RESULT

### ISSUE THREAD

**Issue by YiChenCityU** [akrolic/FAST_ARM64#1]
Hi, was the arm version of fast useless according to your test result?

**Comment by akrolic** [comment]
Hi YiChenCityU,

Yes the test results were successful on the Jetson TX2. Should be able to install this on any other ARM device. 

![TEST RESULT](https://user-images.githubusercontent.com/45604173/100309711-855dd700-2f79-11eb-8144-990814abca8f.png)

There was no officially supported version of FAST for ARM at the time I was working on this. Maybe now there is? 

-akrolic

**Comment by YiChenCityU** [comment]
I found that the opencv 3.4 has already implemented the ARM version of FAST. You can check it.
`opencv3.4.1\opencv\sources\modules\core\include\opencv2\core\hal\intrin_neon.hpp` 
`opencv3.4.1\opencv\sources\modules\features2d\src\fast.cpp`
